<a href="https://colab.research.google.com/github/nikolasmarlon/pandas/blob/main/Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Séries

In [ ]:
import pandas as pd


lista_numeros = [39, 12, 343, 34, 43, 10]

# Series do pandas
serie = pd.Series(lista_numeros) # Retorna índice e valor numa coluna
print(serie)


# Acessar pelo índice
print(serie[2])

0     39
1     12
2    343
3     34
4     43
5     10
dtype: int64
343

In [ ]:
# Criar serie com índice personalizado
index=['a', 'b', 'c', 'd', 'e', 'f']
serie_2 = pd.Series(lista_numeros, index)
print(serie_2)

# Acessar pelo índice personalizado
print(serie_2['c'])

a     39
b     12
c    343
d     34
e     43
f     10
dtype: int64
343

In [ ]:
# Serie a partir de um dicionário

# Dicionário de números
dicionario_numeros = {'a': 1, 'b': 3, 'c': 5, 'd': 7, 'e': 9}
serie_3 = pd.Series(dicionario_numeros)
print(serie_3)

a    1
b    3
c    5
d    7
e    9
dtype: int64

# Dataframes
Estrutura com 2 dimensões - mais usado que series ( ex. parece planilha )

In [ ]:
import pandas as pd

# Dicionário de dados
dados = {
    'Nome': ['João', 'Maria', 'Pedro', 'Ana'],
    'Idade': [25, 49, 18, 43],
    'Cidade': ['São Paulo', 'Rio de Janeiro', 'Belo Horizonte', 'Salvador']
}

# Dataframe
df = pd.DataFrame(dados)
print(df)

print('\n')
# Acessando coluna
print(df['Nome'])

print('\n')
# Acessando linha
print(df.loc[2])

    Nome  Idade          Cidade
0   João     25       São Paulo
1  Maria     49  Rio de Janeiro
2  Pedro     18  Belo Horizonte
3    Ana     43        Salvador


0     João
1    Maria
2    Pedro
3      Ana
Name: Nome, dtype: object


Nome               Pedro
Idade                 18
Cidade    Belo Horizonte
Name: 2, dtype: object

In [ ]:
# Criar um dataframe a partir de uma lista de dicionários

# Lista de dicionários
lista_dicionarios = [
    {'Nome': 'João', 'Idade': 34, 'Cidade': 'São Paulo'},
    {'Nome': 'Maria', 'Idade': 23, 'Cidade': 'Rio de Janeiro'},
    {'Nome': 'Pedro', 'Idade': 45, 'Cidade': 'Belo Horizonte'}
]


# Dataframe
df_2 = pd.DataFrame(lista_dicionarios)
print(df_2)

    Nome  Idade          Cidade
0   João     34       São Paulo
1  Maria     23  Rio de Janeiro
2  Pedro     45  Belo Horizonte

# Ler e salvar no pandas

In [ ]:
import pandas as pd

csv_url = 'https://raw.githubusercontent.com/plotly/datasets/master/gapminderDataFiveYear.csv'

df = pd.read_csv(csv_url)
print(df)

          country  year         pop continent  lifeExp   gdpPercap
0     Afghanistan  1952   8425333.0      Asia   28.801  779.445314
1     Afghanistan  1957   9240934.0      Asia   30.332  820.853030
2     Afghanistan  1962  10267083.0      Asia   31.997  853.100710
3     Afghanistan  1967  11537966.0      Asia   34.020  836.197138
4     Afghanistan  1972  13079460.0      Asia   36.088  739.981106
...           ...   ...         ...       ...      ...         ...
1699     Zimbabwe  1987   9216418.0    Africa   62.351  706.157306
1700     Zimbabwe  1992  10704340.0    Africa   60.377  693.420786
1701     Zimbabwe  1997  11404948.0    Africa   46.809  792.449960
1702     Zimbabwe  2002  11926563.0    Africa   39.989  672.038623
1703     Zimbabwe  2007  12311143.0    Africa   43.487  469.709298

[1704 rows x 6 columns]

In [ ]:
# ler arquivos xlsx
df_xlsx = pd.read_excel('movies.xls')
print(df_xlsx)
#

                                                  Title  Year  \
0     Intolerance: Love's Struggle Throughout the Ages   1916
1                       Over the Hill to the Poorhouse   1920
2                                       The Big Parade   1925
3                                           Metropolis   1927
4                                        Pandora's Box   1929
...                                                 ...   ...
1333                                  Twin Falls Idaho   1999
1334                     Universal Soldier: The Return   1999
1335                                     Varsity Blues   1999
1336                                    Wild Wild West   1999
1337                                    Wing Commander   1999

                            Genres Language  Country Content Rating  Duration  \
0                Drama|History|War      NaN      USA      Not Rated       123
1                      Crime|Drama      NaN      USA            NaN       110
2                Drama|Romance|War      NaN      USA      Not Rated       151
3                     Drama|Sci-Fi   German  Germany      Not Rated       145
4              Crime|Drama|Romance   German  Germany      Not Rated       110
...                            ...      ...      ...            ...       ...
1333                         Drama  English      USA              R       111
1334                 Action|Sci-Fi  English      USA              R        83
1335    Comedy|Drama|Romance|Sport  English      USA              R       106
1336  Action|Comedy|Sci-Fi|Western  English      USA          PG-13       106
1337       Action|Adventure|Sci-Fi  English      USA          PG-13       100

      Aspect Ratio       Budget  Gross Earnings  ... Facebook Likes - Actor 1  \
0             1.33     385907.0             NaN  ...                      436
1             1.33     100000.0       3000000.0  ...                        2
2             1.33     245000.0             NaN  ...                       81
3             1.33    6000000.0         26435.0  ...                      136
4             1.33          NaN          9950.0  ...                      426
...            ...          ...             ...  ...                      ...
1333          1.85     500000.0        985341.0  ...                      980
1334          1.85   24000000.0      10431220.0  ...                     2000
1335          1.85   16000000.0      52885587.0  ...                    23000
1336          1.85  170000000.0     113745408.0  ...                    10000
1337          2.35   30000000.0      11576087.0  ...                      811

     Facebook Likes - Actor 2 Facebook Likes - Actor 3  \
0                          22                      9.0
1                           2                      0.0
2                          12                      6.0
3                          23                     18.0
4                          20                      3.0
...                       ...                      ...
1333                      505                    482.0
1334                      577                    485.0
1335                      255                     35.0
1336                     4000                    582.0
1337                      586                    362.0

     Facebook Likes - cast Total  Facebook likes - Movie  \
0                            481                     691
1                              4                       0
2                            108                     226
3                            203                   12000
4                            455                     926
...                          ...                     ...
1333                        3166                     180
1334                        4024                     401
1335                       23369                       0
1336                       15870                       0
1337                        2497                     858

      Facenumber in posters  User Votes  Reviews by Users  Reviews by Crtiics  \
0                         1       10718                88                69.0
1                         1           5                 1                 1.0
2                         0        4849                45                48.0
3                         1      111841               413               260.0
4                         1        7431                84                71.0
...                     ...         ...               ...                 ...
1333                      0        3479                87                54.0
1334                      0       24216               162                75.0
1335                      0       35312               267                67.0
1336                      2      129601               648                85.0
1337                      3       14747               338                85.0

      IMDB Score
0            8.0
1            4.8
2            8.3
3            8.3
4            8.0
...          ...
1333         7.3
1334         4.1
1335         6.4
1336         4.8
1337         4.1

[1338 rows x 25 columns]

In [ ]:
# Salvar no formato csv

dataframe_exemplo = pd.DataFrame({
    'Nome': ['João', 'Maria', 'Pedro', 'Ana'],
    'Idade': [25, 49, 18, 43],
    'Cidade': ['São Paulo', 'Rio de Janeiro', 'Belo Horizonte', 'Salvador']
})


# Salvar em csv
dataframe_exemplo.to_csv('dataframe_exemplo.csv', index=False) # Index= false para não salvar o índice junto

In [ ]:
# Lendo csv que foi criado
df_csv = pd.read_csv('dataframe_exemplo.csv')
print(df_csv)

    Nome  Idade          Cidade
0   João     25       São Paulo
1  Maria     49  Rio de Janeiro
2  Pedro     18  Belo Horizonte
3    Ana     43        Salvador

In [ ]:
# Salvando como xlsx
dataframe_exemplo.to_excel('dataframe_exemplo.xlsx', index=False)

In [ ]:
# Lendo xlsx criado
df_xlsx = pd.read_excel('dataframe_exemplo.xlsx')
print(df_xlsx)

    Nome  Idade          Cidade
0   João     25       São Paulo
1  Maria     49  Rio de Janeiro
2  Pedro     18  Belo Horizonte
3    Ana     43        Salvador

# Head, Tail, Shape, Info, Describe
Funções do pandas

In [ ]:
import pandas as pd

# Dicionário
dados = {
    'Nome': ['João', 'Maria', 'Pedro', 'Ana'],
    'Idade': [25, 49, 18, 43],
    'Cidade': ['São Paulo', 'Rio de Janeiro', 'Belo Horizonte', 'Salvador'],
    'Salário': [5000, 7000, 3000, 6000]
}

df = pd.DataFrame(dados)
print(df)


print('\n')

    Nome  Idade          Cidade  Salário
0   João     25       São Paulo     5000
1  Maria     49  Rio de Janeiro     7000
2  Pedro     18  Belo Horizonte     3000
3    Ana     43        Salvador     6000

In [ ]:
# Função head(n) - vai retornar as primeiras linhas do dataframe
print(df.head(2)) # Padão retorna 5 linhas se não for informado

    Nome  Idade          Cidade  Salário
0   João     25       São Paulo     5000
1  Maria     49  Rio de Janeiro     7000

In [ ]:
# Função tail() vai retornar as últimas linhas
print(df.tail(2))

    Nome  Idade          Cidade  Salário
2  Pedro     18  Belo Horizonte     3000
3    Ana     43        Salvador     6000

In [ ]:
# Função shape()
print(df.shape) # Retorna (linhas, colunas)

(4, 4)

In [ ]:
# Função info()
print(df.info()) # Retorna informações do dataframe

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Nome     4 non-null      object
 1   Idade    4 non-null      int64
 2   Cidade   4 non-null      object
 3   Salário  4 non-null      int64
dtypes: int64(2), object(2)
memory usage: 260.0+ bytes
None

In [ ]:
# Função describe()
print(df.describe()) # Retorna informações estatísticas do dataframe ( estatística descritiva)

           Idade      Salário
count   4.000000     4.000000
mean   33.750000  5250.000000
std    14.637281  1707.825128
min    18.000000  3000.000000
25%    23.250000  4500.000000
50%    34.000000  5500.000000
75%    44.500000  6250.000000
max    49.000000  7000.000000

# Loc e Iloc
Seleção de dados

In [ ]:
import pandas as pd

#Criar dataframe DF
dados = {
    'Nome': ['João', 'Maria', 'Pedro', 'Ana'],
    'Idade': [25, 34, 21, 44],
    'Cidade': ['São Paulo', 'Rio de Janeiro', 'Belo Horizonte', 'Salvador']
}

# Criar index
index = ['a', 'b', 'c', 'd']

df = pd.DataFrame(dados, index) # Dataframe com índice personalizado
print(df)


# Visualizar colunas específicas
print('\n')
#df.Cidade # Forma 1
df['Cidade'] # Forma 2

    Nome  Idade          Cidade
a   João     25       São Paulo
b  Maria     34  Rio de Janeiro
c  Pedro     21  Belo Horizonte
d    Ana     44        Salvador

a         São Paulo
b    Rio de Janeiro
c    Belo Horizonte
d          Salvador
Name: Cidade, dtype: object

In [ ]:
# Selecionar multiplas colunas
df[['Nome', 'Cidade']]

    Nome          Cidade
a   João       São Paulo
b  Maria  Rio de Janeiro
c  Pedro  Belo Horizonte
d    Ana        Salvador

In [ ]:
# loc - usando rótulos
df.loc['a'] # Retorna a linha com o rótulo 'a'

print('\n')
# Retornando coluna
df.loc[['a', 'b'], ['Nome']] # Retorna o valor da linha 'a' e coluna 'Nome'

    Nome
a   João
b  Maria

In [ ]:
# iloc - index baseado no índice numéricos
df.iloc[0] # Retorna a primeira linha

Nome           João
Idade            25
Cidade    São Paulo
Name: a, dtype: object

In [ ]:
df.iloc[0:2] # Retorna as duas primeiras linhas

    Nome  Idade          Cidade
a   João     25       São Paulo
b  Maria     34  Rio de Janeiro

In [ ]:
# Selecionar linhas 1 e 2 e coluna 1
df.iloc[0:2, 0]

a     João
b    Maria
Name: Nome, dtype: object

# Filtrando dados

In [ ]:
# Dados para o dataframe - nome, idade, cidade, score
dados = {
    'Nome': ['João', 'Maria', 'Pedro', 'Ana', 'Pedro'],
    'Idade': [25, 34, 21, 23, 41],
    'Cidade': ['São Paulo', 'Rio de Janeiro', 'Belo Horizonte', 'Salvador', 'Rio de Janeiro'],
    'Score': [85, 90, 75, 80, 93]
}

# Dataframe
df = pd.DataFrame(dados)
print(df)

    Nome  Idade          Cidade  Score
0   João     25       São Paulo     85
1  Maria     34  Rio de Janeiro     90
2  Pedro     21  Belo Horizonte     75
3    Ana     23        Salvador     80
4  Pedro     41  Rio de Janeiro     93

In [ ]:
# Filtrar pessoas com score maores que 80
df[df['Score'] > 80]

    Nome  Idade          Cidade  Score
0   João     25       São Paulo     85
1  Maria     34  Rio de Janeiro     90
4  Pedro     41  Rio de Janeiro     93

In [ ]:
# Filtar pessoas do RJ com score maior ou igual a 90
df[(df['Cidade'] == 'Rio de Janeiro') & (df['Score'] >= 90)]

    Nome  Idade          Cidade  Score
1  Maria     34  Rio de Janeiro     90
4  Pedro     41  Rio de Janeiro     93

In [ ]:
# Filtrar por pessoas do rio ou são paulo
df[(df['Cidade'] == 'Rio de Janeiro') | (df['Cidade'] == 'São Paulo')]

    Nome  Idade          Cidade  Score
0   João     25       São Paulo     85
1  Maria     34  Rio de Janeiro     90
4  Pedro     41  Rio de Janeiro     93

In [ ]:
# Método isin()
df[df['Cidade'].isin(['Rio de Janeiro', 'São Paulo'])]

    Nome  Idade          Cidade  Score
0   João     25       São Paulo     85
1  Maria     34  Rio de Janeiro     90
4  Pedro     41  Rio de Janeiro     93

# Sort values - ordenar crescente ou decrescente

In [ ]:
import pandas as pd

dados_frutas = {
    'Fruta': ['Maçã', 'Banana', 'Laranja', 'Morango', 'Uva', 'Abacaxi'],
    'Estoque': [100, 150, 80, 200, 120, 50],
    'Preço': [2.50, 1.80, 3.20, 4.00, 5.50, 7.00]
}

df_frutas = pd.DataFrame(dados_frutas)
print(df_frutas)

     Fruta  Estoque  Preço
0     Maçã      100    2.5
1   Banana      150    1.8
2  Laranja       80    3.2
3  Morango      200    4.0
4      Uva      120    5.5
5  Abacaxi       50    7.0

In [ ]:
# Ordenar em ordem crescente
df_frutas.sort_values(by='Estoque')

     Fruta  Estoque  Preço
5  Abacaxi       50    7.0
2  Laranja       80    3.2
0     Maçã      100    2.5
4      Uva      120    5.5
1   Banana      150    1.8
3  Morango      200    4.0

In [ ]:
# Ordenar por preço
df_frutas.sort_values(by='Preço')

     Fruta  Estoque  Preço
1   Banana      150    1.8
0     Maçã      100    2.5
2  Laranja       80    3.2
3  Morango      200    4.0
4      Uva      120    5.5
5  Abacaxi       50    7.0

In [ ]:
# Ordenar em ordem alfabética
df_frutas.sort_values(by='Fruta')

     Fruta  Estoque  Preço
5  Abacaxi       50    7.0
1   Banana      150    1.8
2  Laranja       80    3.2
0     Maçã      100    2.5
3  Morango      200    4.0
4      Uva      120    5.5

In [ ]:
# Ordenar em ordem decrescente por preço
df_frutas.sort_values(by='Preço', ascending=False)

     Fruta  Estoque  Preço
5  Abacaxi       50    7.0
4      Uva      120    5.5
3  Morango      200    4.0
2  Laranja       80    3.2
0     Maçã      100    2.5
1   Banana      150    1.8

In [ ]:
# Ordenar em ordem alfabética decrescente
df_frutas.sort_values(by='Fruta', ascending=False)

     Fruta  Estoque  Preço
4      Uva      120    5.5
3  Morango      200    4.0
0     Maçã      100    2.5
2  Laranja       80    3.2
1   Banana      150    1.8
5  Abacaxi       50    7.0

In [ ]:
# Ordenação múltiplas colunas.
df_frutas.sort_values(by=['Estoque', 'Preço'], ascending=[True, False])

     Fruta  Estoque  Preço
5  Abacaxi       50    7.0
2  Laranja       80    3.2
0     Maçã      100    2.5
4      Uva      120    5.5
1   Banana      150    1.8
3  Morango      200    4.0

# Formatando colunas

In [ ]:
# Criando dataframe
import pandas as pd

dados = {
    'Nome': ['João', 'Maria', 'Pedro', 'Ana'],
    'Idade': [25, 34, 21, 23],
    'Salário': [5000, 7000, 3000, 6000]
}

df = pd.DataFrame(dados)
print(df)

    Nome  Idade  Salário
0   João     25     5000
1  Maria     34     7000
2  Pedro     21     3000
3    Ana     23     6000