# Séries

In [ ]:
import pandas as pd


lista_numeros = [39, 12, 343, 34, 43, 10]

# Series do pandas
serie = pd.Series(lista_numeros) # Retorna índice e valor numa coluna
print(serie)


# Acessar pelo índice
print(serie[2])

0     39
1     12
2    343
3     34
4     43
5     10
dtype: int64
343

In [ ]:
# Criar serie com índice personalizado
index=['a', 'b', 'c', 'd', 'e', 'f']
serie_2 = pd.Series(lista_numeros, index)
print(serie_2)

# Acessar pelo índice personalizado
print(serie_2['c'])

a     39
b     12
c    343
d     34
e     43
f     10
dtype: int64
343

In [ ]:
# Serie a partir de um dicionário

# Dicionário de números
dicionario_numeros = {'a': 1, 'b': 3, 'c': 5, 'd': 7, 'e': 9}
serie_3 = pd.Series(dicionario_numeros)
print(serie_3)

a    1
b    3
c    5
d    7
e    9
dtype: int64

# Dataframes
Estrutura com 2 dimensões - mais usado que series ( ex. parece planilha )

In [ ]:
import pandas as pd

# Dicionário de dados
dados = {
    'Nome': ['João', 'Maria', 'Pedro', 'Ana'],
    'Idade': [25, 49, 18, 43],
    'Cidade': ['São Paulo', 'Rio de Janeiro', 'Belo Horizonte', 'Salvador']
}

# Dataframe
df = pd.DataFrame(dados)
print(df)

print('\n')
# Acessando coluna
print(df['Nome'])

print('\n')
# Acessando linha
print(df.loc[2])

    Nome  Idade          Cidade
0   João     25       São Paulo
1  Maria     49  Rio de Janeiro
2  Pedro     18  Belo Horizonte
3    Ana     43        Salvador


0     João
1    Maria
2    Pedro
3      Ana
Name: Nome, dtype: object


Nome               Pedro
Idade                 18
Cidade    Belo Horizonte
Name: 2, dtype: object

In [ ]:
# Criar um dataframe a partir de uma lista de dicionários

# Lista de dicionários
lista_dicionarios = [
    {'Nome': 'João', 'Idade': 34, 'Cidade': 'São Paulo'},
    {'Nome': 'Maria', 'Idade': 23, 'Cidade': 'Rio de Janeiro'},
    {'Nome': 'Pedro', 'Idade': 45, 'Cidade': 'Belo Horizonte'}
]


# Dataframe
df_2 = pd.DataFrame(lista_dicionarios)
print(df_2)

    Nome  Idade          Cidade
0   João     34       São Paulo
1  Maria     23  Rio de Janeiro
2  Pedro     45  Belo Horizonte

# Ler e salvar no pandas

In [ ]:
import pandas as pd

csv_url = 'https://raw.githubusercontent.com/plotly/datasets/master/gapminderDataFiveYear.csv'

df = pd.read_csv(csv_url)
print(df)

          country  year         pop continent  lifeExp   gdpPercap
0     Afghanistan  1952   8425333.0      Asia   28.801  779.445314
1     Afghanistan  1957   9240934.0      Asia   30.332  820.853030
2     Afghanistan  1962  10267083.0      Asia   31.997  853.100710
3     Afghanistan  1967  11537966.0      Asia   34.020  836.197138
4     Afghanistan  1972  13079460.0      Asia   36.088  739.981106
...           ...   ...         ...       ...      ...         ...
1699     Zimbabwe  1987   9216418.0    Africa   62.351  706.157306
1700     Zimbabwe  1992  10704340.0    Africa   60.377  693.420786
1701     Zimbabwe  1997  11404948.0    Africa   46.809  792.449960
1702     Zimbabwe  2002  11926563.0    Africa   39.989  672.038623
1703     Zimbabwe  2007  12311143.0    Africa   43.487  469.709298

[1704 rows x 6 columns]

In [ ]:
# ler arquivos xlsx
df_xlsx = pd.read_excel('movies.xls')
print(df_xlsx)
#

                                                  Title  Year  \
0     Intolerance: Love's Struggle Throughout the Ages   1916
1                       Over the Hill to the Poorhouse   1920
2                                       The Big Parade   1925
3                                           Metropolis   1927
4                                        Pandora's Box   1929
...                                                 ...   ...
1333                                  Twin Falls Idaho   1999
1334                     Universal Soldier: The Return   1999
1335                                     Varsity Blues   1999
1336                                    Wild Wild West   1999
1337                                    Wing Commander   1999

                            Genres Language  Country Content Rating  Duration  \
0                Drama|History|War      NaN      USA      Not Rated       123
1                      Crime|Drama      NaN      USA            NaN       110
2                Drama|Romance|War      NaN      USA      Not Rated       151
3                     Drama|Sci-Fi   German  Germany      Not Rated       145
4              Crime|Drama|Romance   German  Germany      Not Rated       110
...                            ...      ...      ...            ...       ...
1333                         Drama  English      USA              R       111
1334                 Action|Sci-Fi  English      USA              R        83
1335    Comedy|Drama|Romance|Sport  English      USA              R       106
1336  Action|Comedy|Sci-Fi|Western  English      USA          PG-13       106
1337       Action|Adventure|Sci-Fi  English      USA          PG-13       100

      Aspect Ratio       Budget  Gross Earnings  ... Facebook Likes - Actor 1  \
0             1.33     385907.0             NaN  ...                      436
1             1.33     100000.0       3000000.0  ...                        2
2             1.33     245000.0             NaN  ...                       81
3             1.33    6000000.0         26435.0  ...                      136
4             1.33          NaN          9950.0  ...                      426
...            ...          ...             ...  ...                      ...
1333          1.85     500000.0        985341.0  ...                      980
1334          1.85   24000000.0      10431220.0  ...                     2000
1335          1.85   16000000.0      52885587.0  ...                    23000
1336          1.85  170000000.0     113745408.0  ...                    10000
1337          2.35   30000000.0      11576087.0  ...                      811

     Facebook Likes - Actor 2 Facebook Likes - Actor 3  \
0                          22                      9.0
1                           2                      0.0
2                          12                      6.0
3                          23                     18.0
4                          20                      3.0
...                       ...                      ...
1333                      505                    482.0
1334                      577                    485.0
1335                      255                     35.0
1336                     4000                    582.0
1337                      586                    362.0

     Facebook Likes - cast Total  Facebook likes - Movie  \
0                            481                     691
1                              4                       0
2                            108                     226
3                            203                   12000
4                            455                     926
...                          ...                     ...
1333                        3166                     180
1334                        4024                     401
1335                       23369                       0
1336                       15870                       0
1337                        2497                     858

      Facenumber in posters  User Votes  Reviews by Users  Reviews by Crtiics  \
0                         1       10718                88                69.0
1                         1           5                 1                 1.0
2                         0        4849                45                48.0
3                         1      111841               413               260.0
4                         1        7431                84                71.0
...                     ...         ...               ...                 ...
1333                      0        3479                87                54.0
1334                      0       24216               162                75.0
1335                      0       35312               267                67.0
1336                      2      129601               648                85.0
1337                      3       14747               338                85.0

      IMDB Score
0            8.0
1            4.8
2            8.3
3            8.3
4            8.0
...          ...
1333         7.3
1334         4.1
1335         6.4
1336         4.8
1337         4.1

[1338 rows x 25 columns]

In [ ]:
# Salvar no formato csv

dataframe_exemplo = pd.DataFrame({
    'Nome': ['João', 'Maria', 'Pedro', 'Ana'],
    'Idade': [25, 49, 18, 43],
    'Cidade': ['São Paulo', 'Rio de Janeiro', 'Belo Horizonte', 'Salvador']
})


# Salvar em csv
dataframe_exemplo.to_csv('dataframe_exemplo.csv', index=False) # Index= false para não salvar o índice junto

In [ ]:
# Lendo csv que foi criado
df_csv = pd.read_csv('dataframe_exemplo.csv')
print(df_csv)

    Nome  Idade          Cidade
0   João     25       São Paulo
1  Maria     49  Rio de Janeiro
2  Pedro     18  Belo Horizonte
3    Ana     43        Salvador

In [ ]:
# Salvando como xlsx
dataframe_exemplo.to_excel('dataframe_exemplo.xlsx', index=False)

In [ ]:
# Lendo xlsx criado
df_xlsx = pd.read_excel('dataframe_exemplo.xlsx')
print(df_xlsx)

    Nome  Idade          Cidade
0   João     25       São Paulo
1  Maria     49  Rio de Janeiro
2  Pedro     18  Belo Horizonte
3    Ana     43        Salvador

# Head, Tail, Shape, Info, Describe
Funções do pandas

In [ ]:
import pandas as pd

# Dicionário
dados = {
    'Nome': ['João', 'Maria', 'Pedro', 'Ana'],
    'Idade': [25, 49, 18, 43],
    'Cidade': ['São Paulo', 'Rio de Janeiro', 'Belo Horizonte', 'Salvador'],
    'Salário': [5000, 7000, 3000, 6000]
}

df = pd.DataFrame(dados)
print(df)


print('\n')

    Nome  Idade          Cidade  Salário
0   João     25       São Paulo     5000
1  Maria     49  Rio de Janeiro     7000
2  Pedro     18  Belo Horizonte     3000
3    Ana     43        Salvador     6000

In [ ]:
# Função head(n) - vai retornar as primeiras linhas do dataframe
print(df.head(2)) # Padão retorna 5 linhas se não for informado

    Nome  Idade          Cidade  Salário
0   João     25       São Paulo     5000
1  Maria     49  Rio de Janeiro     7000

In [ ]:
# Função tail() vai retornar as últimas linhas
print(df.tail(2))

    Nome  Idade          Cidade  Salário
2  Pedro     18  Belo Horizonte     3000
3    Ana     43        Salvador     6000

In [ ]:
# Função shape()
print(df.shape) # Retorna (linhas, colunas)

(4, 4)

In [ ]:
# Função info()
print(df.info()) # Retorna informações do dataframe

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Nome     4 non-null      object
 1   Idade    4 non-null      int64
 2   Cidade   4 non-null      object
 3   Salário  4 non-null      int64
dtypes: int64(2), object(2)
memory usage: 260.0+ bytes
None

In [ ]:
# Função describe()
print(df.describe()) # Retorna informações estatísticas do dataframe ( estatística descritiva)

           Idade      Salário
count   4.000000     4.000000
mean   33.750000  5250.000000
std    14.637281  1707.825128
min    18.000000  3000.000000
25%    23.250000  4500.000000
50%    34.000000  5500.000000
75%    44.500000  6250.000000
max    49.000000  7000.000000

# Loc e Iloc
Seleção de dados

In [ ]:
import pandas as pd

#Criar dataframe DF
dados = {
    'Nome': ['João', 'Maria', 'Pedro', 'Ana'],
    'Idade': [25, 34, 21, 44],
    'Cidade': ['São Paulo', 'Rio de Janeiro', 'Belo Horizonte', 'Salvador']
}

# Criar index
index = ['a', 'b', 'c', 'd']

df = pd.DataFrame(dados, index) # Dataframe com índice personalizado
print(df)


# Visualizar colunas específicas
print('\n')
#df.Cidade # Forma 1
df['Cidade'] # Forma 2

    Nome  Idade          Cidade
a   João     25       São Paulo
b  Maria     34  Rio de Janeiro
c  Pedro     21  Belo Horizonte
d    Ana     44        Salvador

a         São Paulo
b    Rio de Janeiro
c    Belo Horizonte
d          Salvador
Name: Cidade, dtype: object

In [ ]:
# Selecionar multiplas colunas
df[['Nome', 'Cidade']]

    Nome          Cidade
a   João       São Paulo
b  Maria  Rio de Janeiro
c  Pedro  Belo Horizonte
d    Ana        Salvador

In [ ]:
# loc - usando rótulos
df.loc['a'] # Retorna a linha com o rótulo 'a'

print('\n')
# Retornando coluna
df.loc[['a', 'b'], ['Nome']] # Retorna o valor da linha 'a' e coluna 'Nome'

    Nome
a   João
b  Maria

In [ ]:
# iloc - index baseado no índice numéricos
df.iloc[0] # Retorna a primeira linha

Nome           João
Idade            25
Cidade    São Paulo
Name: a, dtype: object

In [ ]:
df.iloc[0:2] # Retorna as duas primeiras linhas

    Nome  Idade          Cidade
a   João     25       São Paulo
b  Maria     34  Rio de Janeiro

In [ ]:
# Selecionar linhas 1 e 2 e coluna 1
df.iloc[0:2, 0]

a     João
b    Maria
Name: Nome, dtype: object

# Filtrando dados

In [ ]:
# Dados para o dataframe - nome, idade, cidade, score
dados = {
    'Nome': ['João', 'Maria', 'Pedro', 'Ana', 'Pedro'],
    'Idade': [25, 34, 21, 23, 41],
    'Cidade': ['São Paulo', 'Rio de Janeiro', 'Belo Horizonte', 'Salvador', 'Rio de Janeiro'],
    'Score': [85, 90, 75, 80, 93]
}

# Dataframe
df = pd.DataFrame(dados)
print(df)

    Nome  Idade          Cidade  Score
0   João     25       São Paulo     85
1  Maria     34  Rio de Janeiro     90
2  Pedro     21  Belo Horizonte     75
3    Ana     23        Salvador     80
4  Pedro     41  Rio de Janeiro     93

In [ ]:
# Filtrar pessoas com score maores que 80
df[df['Score'] > 80]

    Nome  Idade          Cidade  Score
0   João     25       São Paulo     85
1  Maria     34  Rio de Janeiro     90
4  Pedro     41  Rio de Janeiro     93

In [ ]:
# Filtar pessoas do RJ com score maior ou igual a 90
df[(df['Cidade'] == 'Rio de Janeiro') & (df['Score'] >= 90)]

    Nome  Idade          Cidade  Score
1  Maria     34  Rio de Janeiro     90
4  Pedro     41  Rio de Janeiro     93

In [ ]:
# Filtrar por pessoas do rio ou são paulo
df[(df['Cidade'] == 'Rio de Janeiro') | (df['Cidade'] == 'São Paulo')]

    Nome  Idade          Cidade  Score
0   João     25       São Paulo     85
1  Maria     34  Rio de Janeiro     90
4  Pedro     41  Rio de Janeiro     93

In [ ]:
# Método isin()
df[df['Cidade'].isin(['Rio de Janeiro', 'São Paulo'])]

    Nome  Idade          Cidade  Score
0   João     25       São Paulo     85
1  Maria     34  Rio de Janeiro     90
4  Pedro     41  Rio de Janeiro     93

# Sort values - ordenar crescente ou decrescente

In [ ]:
import pandas as pd

dados_frutas = {
    'Fruta': ['Maçã', 'Banana', 'Laranja', 'Morango', 'Uva', 'Abacaxi'],
    'Estoque': [100, 150, 80, 200, 120, 50],
    'Preço': [2.50, 1.80, 3.20, 4.00, 5.50, 7.00]
}

df_frutas = pd.DataFrame(dados_frutas)
print(df_frutas)

     Fruta  Estoque  Preço
0     Maçã      100    2.5
1   Banana      150    1.8
2  Laranja       80    3.2
3  Morango      200    4.0
4      Uva      120    5.5
5  Abacaxi       50    7.0

In [ ]:
# Ordenar em ordem crescente
df_frutas.sort_values(by='Estoque')

     Fruta  Estoque  Preço
5  Abacaxi       50    7.0
2  Laranja       80    3.2
0     Maçã      100    2.5
4      Uva      120    5.5
1   Banana      150    1.8
3  Morango      200    4.0

In [ ]:
# Ordenar por preço
df_frutas.sort_values(by='Preço')

     Fruta  Estoque  Preço
1   Banana      150    1.8
0     Maçã      100    2.5
2  Laranja       80    3.2
3  Morango      200    4.0
4      Uva      120    5.5
5  Abacaxi       50    7.0

In [ ]:
# Ordenar em ordem alfabética
df_frutas.sort_values(by='Fruta')

     Fruta  Estoque  Preço
5  Abacaxi       50    7.0
1   Banana      150    1.8
2  Laranja       80    3.2
0     Maçã      100    2.5
3  Morango      200    4.0
4      Uva      120    5.5

In [ ]:
# Ordenar em ordem decrescente por preço
df_frutas.sort_values(by='Preço', ascending=False)

     Fruta  Estoque  Preço
5  Abacaxi       50    7.0
4      Uva      120    5.5
3  Morango      200    4.0
2  Laranja       80    3.2
0     Maçã      100    2.5
1   Banana      150    1.8

In [ ]:
# Ordenar em ordem alfabética decrescente
df_frutas.sort_values(by='Fruta', ascending=False)

     Fruta  Estoque  Preço
4      Uva      120    5.5
3  Morango      200    4.0
0     Maçã      100    2.5
2  Laranja       80    3.2
1   Banana      150    1.8
5  Abacaxi       50    7.0

In [ ]:
# Ordenação múltiplas colunas.
df_frutas.sort_values(by=['Estoque', 'Preço'], ascending=[True, False])

     Fruta  Estoque  Preço
5  Abacaxi       50    7.0
2  Laranja       80    3.2
0     Maçã      100    2.5
4      Uva      120    5.5
1   Banana      150    1.8
3  Morango      200    4.0

# Formatando colunas

In [ ]:
# Criando dataframe
import pandas as pd

dados = {
    'Nome': ['João', 'Maria', 'Pedro', 'Ana'],
    'Idade': [25, 34, 21, 23],
    'Salário': [5000, 7000, 3000, 6000]
}

df = pd.DataFrame(dados)
print(df)

    Nome  Idade  Salário
0   João     25     5000
1  Maria     34     7000
2  Pedro     21     3000
3    Ana     23     6000

In [ ]:
# Criando nova coluna
df['Salário Formatado'] = df['Salário'].apply(lambda x: f'R$ {x:,.2f}')
print(df)

    Nome  Idade  Salário Salário Formatado
0   João     25     5000       R$ 5,000.00
1  Maria     34     7000       R$ 7,000.00
2  Pedro     21     3000       R$ 3,000.00
3    Ana     23     6000       R$ 6,000.00

In [ ]:
# Criando valor fixo
df['Desconto INSS'] = 0.8
print(df)

    Nome  Idade  Salário Salário Formatado  Desconto INSS
0   João     25     5000       R$ 5,000.00            0.8
1  Maria     34     7000       R$ 7,000.00            0.8
2  Pedro     21     3000       R$ 3,000.00            0.8
3    Ana     23     6000       R$ 6,000.00            0.8

In [ ]:
# Renomear coluna desconto inss
df.rename(columns={'Desconto INSS': 'Desconto INSS %'}, inplace=True)
print(df)

    Nome  Idade  Salário Salário Formatado  Desconto INSS %
0   João     25     5000       R$ 5,000.00              0.8
1  Maria     34     7000       R$ 7,000.00              0.8
2  Pedro     21     3000       R$ 3,000.00              0.8
3    Ana     23     6000       R$ 6,000.00              0.8

In [ ]:
# Removendo colunas
df.drop(columns=['Desconto INSS %'], inplace=True)
print(df)

    Nome  Idade  Salário Salário Formatado
0   João     25     5000       R$ 5,000.00
1  Maria     34     7000       R$ 7,000.00
2  Pedro     21     3000       R$ 3,000.00
3    Ana     23     6000       R$ 6,000.00

In [ ]:
# Removendo mais de uma coluna
df.drop(columns=['Idade', 'Salário'], inplace=True)
print(df)

    Nome Salário Formatado
0   João       R$ 5,000.00
1  Maria       R$ 7,000.00
2  Pedro       R$ 3,000.00
3    Ana       R$ 6,000.00

In [ ]:
print(df)

    Nome Salário Formatado
0   João       R$ 5,000.00
1  Maria       R$ 7,000.00
2  Pedro       R$ 3,000.00
3    Ana       R$ 6,000.00

# Tratamento de dados - Astype, Isna, Fillna e Dropna

In [ ]:
# Criar dataframe
import pandas as pd
import numpy as np # bom para trabalhar com dados ausentes

dados = {
    'Nome': ['João', 'Maria', 'Pedro', 'Ana'],
    'Idade': ['25', '34', '21', '23'],
    'Salário': [5000.75, 1700.20, 3000.99, 6000],
    'Cidade': ['São Paulo', 'Rio de Janeiro', np.nan, 'Salvador']
}

df = pd.DataFrame(dados)
print(df)

    Nome Idade  Salário          Cidade
0   João    25  5000.75       São Paulo
1  Maria    34  1700.20  Rio de Janeiro
2  Pedro    21  3000.99             NaN
3    Ana    23  6000.00        Salvador

In [ ]:
# pandas entende string como objeto( object )
# Ferificar tipo
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Nome     4 non-null      object
 1   Idade    4 non-null      object
 2   Salário  4 non-null      float64
 3   Cidade   3 non-null      object
dtypes: float64(1), object(3)
memory usage: 260.0+ bytes

In [ ]:
# Converter idade 'string' para 'int'
df.Idade = df.Idade.astype(int)

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Nome     4 non-null      object
 1   Idade    4 non-null      int64
 2   Salário  4 non-null      float64
 3   Cidade   3 non-null      object
dtypes: float64(1), int64(1), object(2)
memory usage: 260.0+ bytes

In [ ]:
print(df)

    Nome  Idade  Salário          Cidade
0   João     25  5000.75       São Paulo
1  Maria     34  1700.20  Rio de Janeiro
2  Pedro     21  3000.99             NaN
3    Ana     23  6000.00        Salvador

In [ ]:
# Converter salário para int -- float para int -- obs. não arredonda. pega a parte inteira
df.Salário = df.Salário.astype(int)
print(df)

    Nome  Idade  Salário          Cidade
0   João     25     5000       São Paulo
1  Maria     34     1700  Rio de Janeiro
2  Pedro     21     3000             NaN
3    Ana     23     6000        Salvador

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Nome     4 non-null      object
 1   Idade    4 non-null      int64
 2   Salário  4 non-null      int64
 3   Cidade   3 non-null      object
dtypes: int64(2), object(2)
memory usage: 260.0+ bytes

In [ ]:
# Valores ausentes
# Retornar um dataframe com valores booleanos com isna()
print(df.isna())

    Nome  Idade  Salário  Cidade
0  False  False    False   False
1  False  False    False   False
2  False  False    False    True
3  False  False    False   False

In [ ]:
# fillna() permite prencher algum valor ausente com algum valor

# ex. preencher com 0 onde tem valores nulos
df_nulos = df.fillna({'Cidade': 'Não informado'}) # passar um dicionário
print(df_nulos)

    Nome  Idade  Salário          Cidade
0   João     25     5000       São Paulo
1  Maria     34     1700  Rio de Janeiro
2  Pedro     21     3000   Não informado
3    Ana     23     6000        Salvador

In [ ]:
# Dataframe com valores de salário ausentes do tipo string
dados_ausentes = {
    'Nome': ['João', 'Maria', 'Pedro', 'Ana'],
    'Idade': [25, 34, 21, 23],
    'Salário': [5000.75, 1700.20, np.nan, 6000],
    'Desconto': [0.3, 0.44, 0.88, np.nan]
}

df_ausentes = pd.DataFrame(dados_ausentes)
print(df_ausentes)

    Nome  Idade  Salário  Desconto
0   João     25  5000.75      0.30
1  Maria     34  1700.20      0.44
2  Pedro     21      NaN      0.88
3    Ana     23  6000.00       NaN

In [ ]:
# Preencher salário com média de valores da coluna
media_salario = df_ausentes.fillna({'Salário': df_ausentes.Salário.mean()})
print(media_salario)

    Nome  Idade  Salário  Desconto
0   João     25  5000.75      0.30
1  Maria     34  1700.20      0.44
2  Pedro     21  4233.65      0.88
3    Ana     23  6000.00       NaN

In [ ]:
# Preencher salário com mediana dos valores da coluna
mediana_salario = df_ausentes.fillna({'Desconto': df_ausentes.Desconto.median()})
print(mediana_salario)

    Nome  Idade  Salário  Desconto
0   João     25  5000.75      0.30
1  Maria     34  1700.20      0.44
2  Pedro     21      NaN      0.88
3    Ana     23  6000.00      0.44

In [ ]:
# Remover linhas
df_drop_linhas = df_ausentes.dropna()
print(df_drop_linhas)

    Nome  Idade  Salário  Desconto
0   João     25  5000.75      0.30
1  Maria     34  1700.20      0.44

In [ ]:
# Remover colunhas
df_drop_colunas = df_ausentes.dropna(axis=1) # axis=1 é coluna
print(df_drop_colunas)

    Nome  Idade
0   João     25
1  Maria     34
2  Pedro     21
3    Ana     23

# aplicar função em eixos

In [ ]:
import pandas as pd
dados = {
    'Nome': ['João', 'Maria', 'Pedro', 'Ana'],
    'Idade': [25, 34, 21, 23],
    'Status': ['Ativo', 'Inativo', 'Ativo', 'Inativo']
}

df = pd.DataFrame(dados)
print(df)

    Nome  Idade   Status
0   João     25    Ativo
1  Maria     34  Inativo
2  Pedro     21    Ativo
3    Ana     23  Inativo

In [ ]:
# apply  - criar função para verificar se a pessoa é jovem ou adulto

def categoria_idade ( idade ):
  if idade < 30:
    return 'Jovem'
  else:
    return 'Adulto'

df['Categoria_Idade'] = df['Idade'].apply(categoria_idade)
print(df)

    Nome  Idade   Status Categoria_Idade
0   João     25    Ativo           Jovem
1  Maria     34  Inativo          Adulto
2  Pedro     21    Ativo           Jovem
3    Ana     23  Inativo           Jovem

In [ ]:
# Map


# Dicionário
mapeamento_status = { 'Ativo': 'ATIVO', 'Inativo': 'INATIVO'}

# Aplicar mapeamento
df['Status_Mapeado'] = df['Status'].map(mapeamento_status)
print(df)

    Nome  Idade   Status Categoria_Idade Status_Mapeado
0   João     25    Ativo           Jovem          ATIVO
1  Maria     34  Inativo          Adulto        INATIVO
2  Pedro     21    Ativo           Jovem          ATIVO
3    Ana     23  Inativo           Jovem        INATIVO

In [ ]:
# Apply com função lambda
# Função para dobrar a idade
df['Dobro_Idade'] = df['Idade'].apply(lambda x: x * 2)
print(df)

    Nome  Idade   Status Categoria_Idade Status_Mapeado  Dobro_Idade
0   João     25    Ativo           Jovem          ATIVO           50
1  Maria     34  Inativo          Adulto        INATIVO           68
2  Pedro     21    Ativo           Jovem          ATIVO           42
3    Ana     23  Inativo           Jovem        INATIVO           46

# Funções de agregação
serve para resumir e analisar, agrupar dados em uma coluna, ... agrupar por cidade, agrupar por cidade.

In [ ]:
import pandas as pd

dados = {
    'Nome': ['João', 'Maria', 'Pedro', 'Ana', 'João', 'Maria'],
    'Cidade': ['São Paulo', 'Rio de Janeiro', 'Belo Horizonte', 'Salvador', 'São Paulo', 'Rio de Janeiro'],
    'Idade': [25, 34, 2, 21, 23, 44],
    'Salário': [5000, 7000, 3000, 6000, 5000, 7000]
}

df = pd.DataFrame(dados)
print(df)

    Nome          Cidade  Idade  Salário
0   João       São Paulo     25     5000
1  Maria  Rio de Janeiro     34     7000
2  Pedro  Belo Horizonte      2     3000
3    Ana        Salvador     21     6000
4   João       São Paulo     23     5000
5  Maria  Rio de Janeiro     44     7000

In [ ]:
# Agrupar por cidade e calcular a soma dos salarios
vendas_por_cidade = df.groupby('Cidade')['Salário'].sum()
print(vendas_por_cidade)
#

Cidade
Belo Horizonte     3000
Rio de Janeiro    14000
Salvador           6000
São Paulo         10000
Name: Salário, dtype: int64

In [ ]:
# Agrupar por cidade e ver a média de idade e salários
media_idade_salario_por_cidade = df.groupby('Cidade')[['Idade', 'Salário']].mean()
print(media_idade_salario_por_cidade)

                Idade  Salário
Cidade
Belo Horizonte    2.0   3000.0
Rio de Janeiro   39.0   7000.0
Salvador         21.0   6000.0
São Paulo        24.0   5000.0

# Funções de datas

In [3]:
# Criar dataframe
import pandas as pd
dados = {
    'Data': ['2023-07-01', '2023-07-02', '2023-07-03', '2023-07-04', '2023-07-05'],
    'evento': ['Evento A', 'Evento B', 'Evento C', 'Evento D', 'Evento E'],

}

df = pd.DataFrame(dados)
print(df)

         Data    evento
0  2023-07-01  Evento A
1  2023-07-02  Evento B
2  2023-07-03  Evento C
3  2023-07-04  Evento D
4  2023-07-05  Evento E

In [4]:
# Dtypes - tudo que for do tipo string o pandas retorna como objeto.
print(df.dtypes)

Data      object
evento    object
dtype: object

In [5]:
# converter para o formato data
df['Data'] = pd.to_datetime(df['Data'])# Convete uma coluna para o formato data
print(df.dtypes)

Data      datetime64[ns]
evento            object
dtype: object

In [21]:
# Lidar com formatos diferentes de datas
df_data_formatos = pd.DataFrame({
    'Data': ['01/02/2022', '02-Jan-2026', '20230604'],
    'Valor': [10, 20, 30]
})

print(df_data_formatos)
print(df_data_formatos.dtypes)

          Data  Valor
0   01/02/2022     10
1  02-Jan-2026     20
2     20230604     30
Data     object
Valor     int64
dtype: object

In [22]:
# converter formatos diferentes
df_data_formatos['Data_convertida'] = pd.to_datetime(df_data_formatos['Data'], format='mixed')
print(df_data_formatos.dtypes)

print(df_data_formatos)

Data                       object
Valor                       int64
Data_convertida    datetime64[ns]
dtype: object
          Data  Valor Data_convertida
0   01/02/2022     10      2022-01-02
1  02-Jan-2026     20      2026-01-02
2     20230604     30      2023-06-04

In [24]:
# Extrair valores

df_data_formatos['Ano'] = df_data_formatos['Data_convertida'].dt.year
df_data_formatos['Mês'] = df_data_formatos['Data_convertida'].dt.month
df_data_formatos['Dia'] = df_data_formatos['Data_convertida'].dt.day
df_data_formatos['Hora'] = df_data_formatos['Data_convertida'].dt.hour
df_data_formatos['Minuto'] = df_data_formatos['Data_convertida'].dt.minute
df_data_formatos['Segundo'] = df_data_formatos['Data_convertida'].dt.second
df_data_formatos['Dia_da_semana'] = df_data_formatos['Data_convertida'].dt.day_name()

print(df_data_formatos)
#

          Data  Valor Data_convertida   Ano  Mês  Dia  Hora  Minuto  Segundo  \
0   01/02/2022     10      2022-01-02  2022    1    2     0       0        0
1  02-Jan-2026     20      2026-01-02  2026    1    2     0       0        0
2     20230604     30      2023-06-04  2023    6    4     0       0        0

  Dia_da_semana
0        Sunday
1        Friday
2        Sunday

In [30]:
# Criando dados e data Frame
dados = {
    'Data': ['2022-01-01', '2025-04-02', '2023-07-03', '2023-05-04', '2024-12-05'],
    'evento': ['Evento A', 'Evento B', 'Evento C', 'Evento D', 'Evento E'],

}

df = pd.DataFrame(dados)
print(df)

         Data    evento
0  2022-01-01  Evento A
1  2025-04-02  Evento B
2  2023-07-03  Evento C
3  2023-05-04  Evento D
4  2024-12-05  Evento E

In [31]:
# Filtrar por uma data específica
data_filtrada = df[df['Data'] == '2023-07-03']
print(data_filtrada)

         Data    evento
2  2023-07-03  Evento C

In [33]:
# Filtrar por intervalo
data_filtrada2 = df[(df['Data'] >= '2023-01-01') & (df['Data'] <= '2024-12-07')]
print(data_filtrada2)

         Data    evento
2  2023-07-03  Evento C
3  2023-05-04  Evento D
4  2024-12-05  Evento E

In [34]:
# Filtrar por intervalo de data com between()
data_filtrada3 = df[df['Data'].between('2023-01-01', '2024-12-07')]
print(data_filtrada3)

         Data    evento
2  2023-07-03  Evento C
3  2023-05-04  Evento D
4  2024-12-05  Evento E

# Concatenar objetos dos pandas colunas por coluna ou linhas com concat()

In [6]:
# Criando dois dataframes
import pandas as pd

df1 = pd.DataFrame({'A': [1, 2, 3], 'B': [4, 5, 6]})
df2 = pd.DataFrame({'C': [7, 8, 9], 'D': [10, 11, 12]})

print(df1)
print(df2)

   A  B
0  1  4
1  2  5
2  3  6
   C   D
0  7  10
1  8  11
2  9  12

In [9]:
# Concatenando por colunas
df_concatenado = pd.concat([df1, df2], axis=1)
print(df_concatenado)

   A  B  C   D
0  1  4  7  10
1  2  5  8  11
2  3  6  9  12

In [11]:
# Concatenando por linhas
df_concatenado2 = pd.concat([df1, df2])
print(df_concatenado2)

     A    B    C     D
0  1.0  4.0  NaN   NaN
1  2.0  5.0  NaN   NaN
2  3.0  6.0  NaN   NaN
0  NaN  NaN  7.0  10.0
1  NaN  NaN  8.0  11.0
2  NaN  NaN  9.0  12.0

# Merge - combinar dataframes

In [5]:
# criar data frame
import pandas as pd

df1 = pd.DataFrame({'chave': ['A', 'B', 'C', 'D'], 'valor1': [1, 2, 3, 5]})
df2 = pd.DataFrame({'chave': ['B', 'D', 'E', 'F'], 'valor2': [6, 7, 8, 9]})

print(df1)
print(df2)

  chave  valor1
0     A       1
1     B       2
2     C       3
3     D       5
  chave  valor2
0     B       6
1     D       7
2     E       8
3     F       9

In [6]:
# Merge Inner combinar pela chave
df_merge = pd.merge(df1, df2, on='chave', how='inner') # inner é o padrão
print(df_merge)

  chave  valor1  valor2
0     B       2       6
1     D       5       7

In [7]:
# left merge
merge_left = pd.merge(df1, df2, on='chave', how='left')
print(merge_left) # Quando não tem associação ele coloca o valor nulo

  chave  valor1  valor2
0     A       1     NaN
1     B       2     6.0
2     C       3     NaN
3     D       5     7.0

In [8]:
# right merge
merge_right = pd.merge(df1, df2, on='chave', how='right')
print(merge_right)

  chave  valor1  valor2
0     B     2.0       6
1     D     5.0       7
2     E     NaN       8
3     F     NaN       9

In [9]:
# Outer merge
merge_outer = pd.merge(df1, df2, on='chave', how='outer')
print(merge_outer)

  chave  valor1  valor2
0     A     1.0     NaN
1     B     2.0     6.0
2     C     3.0     NaN
3     D     5.0     7.0
4     E     NaN     8.0
5     F     NaN     9.0